
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sdlc
spring.datasource.username=postgres
spring.datasource.password=suresh@46

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true    

jwt.secret=SDLCBackendAppSecretKey2026ForJwtTokenSigningPurposeOnly


# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sureshkumar.ramamoorthy01@gmail.com
spring.mail.password=erub lukf tbor xbns

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true